version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: easyappointments-database
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=easyappointments
        ports:
            - "8001:3306"
        platform: linux/amd64
    server:
        build: ./server
        image: easyappointments-server:v1
        container_name: easyappointments-server
        ports:
            - "8000:80"
        volumes:
            - ../:/var/www/html
            - ./server/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    cron:
        image: easyappointments-server:v1
        entrypoint: /bin/bash
        command: ["cron"]
        volumes:
            - ./log/cron/cron.log:/var/log/cron/cron.log